apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  # General
  TIMEZONE: America/Denver
  # IP Addresses
  FS1_IP: "10.0.0.10"
  BLOCKY_IP: "10.0.0.153"
  WG_EASY_IP: "10.0.0.177"
  # Paths
  AUDIO_PATH: "/mnt/zpool1/audio"
  BOOKS_PATH: "/mnt/zpool1/books"
  MOVIES_PATH: "/mnt/zpool1/movies"
  TVSHOWS_PATH: "/mnt/zpool1/tv-shows"
  DOWNLOADS_PATH: "/mnt/zpool1/temp/downloads"
  NVR_PATH: "/mnt/zpool4/nvr"
